parameters:
#    harvest_cloud_core.example.class: HarvestCloud\CoreBundle\Example
    harvest_cloud_core.exchange_manager.class: HarvestCloud\CoreBundle\ExchangeManager
    harvest_cloud_core.profile_handler.class:  HarvestCloud\CoreBundle\Handler\ProfileHandler
    harvest_cloud_core.login_listener.class:   HarvestCloud\CoreBundle\Listener\LoginListener

services:
#    harvest_cloud_core.example:
#        class: %harvest_cloud_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    exchange_manager:
        class:     %harvest_cloud_core.exchange_manager.class%
        arguments: [@doctrine]

    profile_handler:
        class:     %harvest_cloud_core.profile_handler.class%
        arguments: [@doctrine, @security.context, @session]

    login_listener:
        class:     %harvest_cloud_core.login_listener.class%
        arguments: [@doctrine, @session]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: postLogin }

