parameters:
#    harvest_cloud_core.example.class: HarvestCloud\CoreBundle\Example
    harvest_cloud_core.exchange_manager.class: HarvestCloud\CoreBundle\ExchangeManager

services:
#    harvest_cloud_core.example:
#        class: %harvest_cloud_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    exchange_manager:
        class:     %harvest_cloud_core.exchange_manager.class%
        arguments: [@doctrine]
