Hub_homepage:
    pattern:  /
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\DefaultController::indexAction }


Hub_register_landing:
    pattern:  /register/landing
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\RegisterController::landingAction }


Hub_order:
    pattern:  /orders
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\OrderController::indexAction }

Hub_order_receive:
    pattern:  /order/{id}/receive
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\OrderController::receiveAction }
    requirements:
        id: \d+
        _method: POST

Hub_order_mark_as_ready_to_pickup:
    pattern:  /order/{id}/mark-as-ready-to-pickup
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\OrderController::mark_as_ready_to_pickupAction }
    requirements:
        id: \d+
        _method: POST

Hub_order_release:
    pattern:  /order/{id}/release
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\OrderController::releaseAction }
    requirements:
        id: \d+
        _method: POST



Hub_window_maker:
    pattern:  /window-maker
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\WindowMakerController::indexAction }
    requirements:
        _method: GET

Hub_window_maker_create:
    pattern:  /window-maker/new
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\WindowMakerController::newAction }
    requirements:
        _method: POST

Hub_window_maker_new:
    pattern:  /window-maker/new
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\WindowMakerController::newAction }
    requirements:
        _method: GET

Hub_window_maker_update:
    pattern:  /window-maker/{id}/edit
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\WindowMakerController::editAction }
    requirements:
        _method: POST

Hub_window_maker_edit:
    pattern:  /window-maker/{id}/edit
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\WindowMakerController::editAction }
    requirements:
        _method: GET

Hub_window_maker_show:
    pattern:  /window-maker/{id}
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\WindowMakerController::showAction }
    requirements:
        id: \d+
        _method: GET

Hub_window_maker_make:
    pattern:  /window-maker/{id}/make
    defaults: { _controller: HarvestCloud\CoreBundle\Controller\Hub\WindowMakerController::showAction }
    requirements:
        id: \d+
        _method: POST
